

    .code

main PROC

    ; prelude - create stack frame and shadow area
    push rbp ; save base of current stack frame to restore it later
    mov rbp, rsp ; set new base of new stack frame (to current stack pointer)
    sub rsp, 8 * (4 + 2) ; allocate shadow register area + 2 QWORDs for stack alignment    ; Function Preamble - save space on stack for all local variables - [AsmAstConversionVisitor::visit_tacky_function()]    ; + Updated in AsmAstFixupVisitor::visit_asm_ast_function()
    sub rsp, 16
    mov qword ptr [rbp-4], 1
    mov qword ptr [rbp-8], 2
    mov r10d, qword ptr [rbp-8]
    mov qword ptr [rbp-12], r10d
    mov r10d, qword ptr [rbp-16]
    add dword ptr [rbp-12], r10d
    mov rax, 0    ; Generated by the Return keyword in asm_ast_conversion_visitor

    ; epilog - restore stack pointer
    mov rsp, rbp
    pop rbp

    ; pops the return address from the top of the stack into the instruction pointer (EIP/RIP)
    ret
main ENDP

END
