use crate::tacky::tacky::Program;
use crate::tacky::tacky::TopLevel;
use crate::tacky::tacky::TopLevelType;
use crate::tacky::tacky::ValueElement;
use crate::tacky::tacky::Instruction;
use crate::tacky::tacky::InstructionType;
use crate::tacky::tacky::UnaryOperator;
use crate::tacky::tacky::BinaryOperator;

use crate::AsmAstProgram;
use crate::asm_ast::asm_ast::AsmAstFunction;
use crate::asm_ast::asm_ast::AsmAstInstruction;
use crate::asm_ast::asm_ast::AsmAstInstructionType;
use crate::asm_ast::asm_ast::AsmAstReg;
use crate::asm_ast::asm_ast::AsmAstOperand;
use crate::asm_ast::asm_ast::AsmAstOperandType;
use crate::asm_ast::asm_ast::AsmAstUnaryOperator;
use crate::asm_ast::asm_ast::AsmAstBinaryOperator;

use crate::c_ast::ast_node::AstNodeOperatorType;

use crate::common::data_type::DataType;

//
// Converts or lowers a TACKY application into an ASM AST (of precursor/pseudo ASM instructions).
// The TACKY code is generated by the TackyVisitor.
//
// 1. c_ast/IdentifierResolutionVisitor - checks for duplicate or undeclared variable names
// 2. tacky/TackyVisitor - Generate TACKY (from AST)
// 3. asm_ast/AsmAstConversionVisitor - (This struct) Converts the AST into a ASM AST for assembly with a precursory form of mnenomics
// 4. asm_ast/AsmAstFixupVisitor - replacing pseudo operands/variables with stack addresses
// 5. asm_ast/AsmAstMasmEmitterVisitor / asm_ast/AsmAstASEmitterVisitor / ...
//
// This visitor generates a precursory form of real assembly instructions.
// For each indidivual line of TACKY instruction, it prepares one or more precursor assembly instructions 
// that are required to execute functionality that the TACKY instruction hints at. 
//
// e.g. div, remainder/module, mul, ... need to arrange parameters and execute data type 
// conversion (cdq, ...) before finally executing the arithmetic mnemonic. This visitor
// will prepare all the pseudo mnemonics required to execute each TACKY function/line.
//

// see asm_ast.rs
//let SYSTEM_V_ABI_REGISTER_ORDER = [ "DI", "SI", "DX", "CX", "R8", "R9" ];
static SYSTEM_V_ABI_REGISTER_ORDER: [AsmAstReg; 6] = [ AsmAstReg::DI, AsmAstReg::SI, AsmAstReg::DX, AsmAstReg::CX, AsmAstReg::R8, AsmAstReg::R9 ];

pub struct AsmAstConversionVisitor {
    pub asm_ast_program: AsmAstProgram,
}

impl AsmAstConversionVisitor {

    pub fn new() -> AsmAstConversionVisitor {
        AsmAstConversionVisitor {
            asm_ast_program: AsmAstProgram::new(),
        }
    }

    // util
    pub fn move_src_to_ax(&mut self, tacky_instruction: &Instruction) -> AsmAstInstruction {

        let mut mov: AsmAstInstruction = AsmAstInstruction::new();
        mov.instruction_type = AsmAstInstructionType::Mov;

        match &tacky_instruction.src {

            ValueElement::Constant(constant_value) => {
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }

            ValueElement::Variable(variable_name) => {
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }

            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_instruction.src).as_str());
            }
        }

        mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::AX) };

        mov
    }

    pub fn visit_tacky_program(&mut self, tacky_node_program: &Program) {
        println!("[AsmAstConversionVisitor::visit_tacky_program()]");

        self.asm_ast_program.name = tacky_node_program.name.clone();
        
        for i in 0..tacky_node_program.top_level.len() {

            let temp_top_level_item:&Box<TopLevel> = &tacky_node_program.top_level[i];

            match &temp_top_level_item.as_ref().top_level_type {

                TopLevelType::Function => {
                    self.visit_tacky_function(&temp_top_level_item.as_ref());
                }

                TopLevelType::StaticVariable => {
                    todo!("TopLevelType::StaticVariable");
                }

                TopLevelType::StaticConstant => {
                    todo!("TopLevelType::StaticConstant");
                }
            }
        }
    }

    pub fn visit_tacky_function(&mut self, tacky_node_top_level_function: &TopLevel) {

        let function_name = tacky_node_top_level_function.name.clone();

        println!("[AsmAstConversionVisitor::visit_tacky_function()] {}", &function_name);

        let mut asm_ast_function: AsmAstFunction = AsmAstFunction::new();
        asm_ast_function.name = function_name.clone();

        if tacky_node_top_level_function.return_type.is_some() {
            asm_ast_function.return_type = Some(tacky_node_top_level_function.return_type.clone().expect("REASON"));
        }

        // ALLOCATE_STACK
        // insert allocate stack instruction - page 42
        //
        // placeholder to reserve space for local variables
        // This instruction is later updated inside the AsmAstFixupVisitor::visit_asm_ast_function()
        let mut asm_ast_allocate_stack: AsmAstInstruction = AsmAstInstruction::new();
        asm_ast_allocate_stack.instruction_type = AsmAstInstructionType::AllocateStack;
        asm_ast_allocate_stack.comment = String::from("    ; Function Preamble - save space on stack for all local variables - [AsmAstConversionVisitor::visit_tacky_function()]");
        asm_ast_function.body.push(Box::new(asm_ast_allocate_stack));

        //
        // Nora Sandler, page 196
        //
        // Copy all function parameters which are located in registers onto the stack so that there is no need
        // to store and restore registers to keep the parameters alive as the function executes.
        //
        // (System-V ABI, the first six registers ("DI", "SI", "DX", "CX", "R8", "R9") 
        // and Win64 FastCall, the first 4 registers (RCX, RDX, R8 and R9))
        // 
        // To achieve this, the amount of parameters has to be known and move instructions
        // to stack addresses need to be emitted. 
        // 
        // How to formulate the stack addresses? 
        //

        println!("Function {:?} has {} formal arguments!", &function_name, tacky_node_top_level_function.arguments.len());
        println!("SYSTEM_V_ABI_REGISTER_ORDER: {:?}", SYSTEM_V_ABI_REGISTER_ORDER);
        
        for (i, param) in tacky_node_top_level_function.arguments.iter().enumerate() {

            // System-V ABI
            // only process arguments 0 ot 5, the rest of the arguments is on the stack already
            if i > 5 {
                continue;
            }

            // exlude void
            if param.data_type == DataType::DataTypeVoid {
                continue;
            }

            // DEBUG
            println!("Parameter {:?}) {:?} is located in register {:?}", i, param, SYSTEM_V_ABI_REGISTER_ORDER[i]);

            //todo: generate move commands for each of the first n ABI registers into a stack address!
            //where and how are the stack addresses computed?

            // This function is part of the AsmAstConversionVisitor (this struct) which is followed by the 
            // AsmAstFixupVisitor. The AsmAstFixupVisitor has the purpose of generating addresses for 
            // AsmAstOperandType::Pseudo defined in asm_ast.rs

            //
            // Mov
            //

            let mut mov: AsmAstInstruction = AsmAstInstruction::new();
            mov.instruction_type = AsmAstInstructionType::Mov;
            mov.comment = String::from(format!("    ; Parameter {:?}) {:?} is located in register {:?}", i, param, SYSTEM_V_ABI_REGISTER_ORDER[i]).to_string());

            mov.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(SYSTEM_V_ABI_REGISTER_ORDER[i].clone()) };

            // match param.as_ref() {
            //     ValueElement::Constant(constant_value) => {
            //         mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            //     }
            //     ValueElement::Variable(variable_name) => {
            //         mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            //     }
            //     _ => {
            //         panic!("{}", format!("Unhandled InstructionType {:?}!\n", param).as_str());
            //     }
            // }

            // match &tacky_node_copy.dst {
            //     ValueElement::Variable(variable_name) => {
            //         mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            //     }
            //     _ => {
            //         panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_copy.dst).as_str());
            //     }
            // }

            // mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(SYSTEM_V_ABI_REGISTER_ORDER[index].clone()) };

            // Nora Sandler, page 196 says to use Pseudo("param")
            // mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(String::from("param")) };

            let new_param_variable_name = format!("param_{}", i);
            // mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(new_param_variable_name) };
            mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(param.name.clone()) };

            asm_ast_function.body.push(Box::new(mov));
        }

        //
        // BODY
        //

        // emit all instructions in the body
        for i in 0..tacky_node_top_level_function.body.len() {

            let tacky_instruction:&Instruction = &tacky_node_top_level_function.body[i].as_ref();
            match tacky_instruction.instruction_type {

                InstructionType::Comment => {
                }

                InstructionType::Unary => {
                    self.visit_tacky_unary(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::Binary => {
                    self.visit_tacky_binary(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::Return => {
                    self.visit_tacky_return(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::JumpIfZero => {
                    self.visit_tacky_jump_if_zero(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::Label => {
                    self.visit_tacky_label(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::VariableDeclaration => {
                    self.visit_tacky_variable_declaration(&mut asm_ast_function);
                }

                InstructionType::Copy => {
                    self.visit_tacky_copy(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::Jump => {
                    self.visit_tacky_jump(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::FunCall => {
                    self.visit_tacky_fun_call_system_v_abi(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::GetAddress => {
                    self.visit_tacky_get_address(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::Load => {
                    self.visit_tacky_load(&mut asm_ast_function, tacky_instruction);
                }

                InstructionType::Store => {
                    self.visit_tacky_store(&mut asm_ast_function, tacky_instruction);
                }

                _ => {
                    panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_instruction.instruction_type).as_str());
                }
            }
        }

        // // deallocate stack
        // let mut deallocate_stack: AsmAstInstruction = AsmAstInstruction::new();
        // deallocate_stack.instruction_type = AsmAstInstructionType::DeallocateStack;
        // deallocate_stack.src.operand_type = AsmAstOperandType::Imm(120 as i32);

        // asm_ast_function.body.push(Box::new(deallocate_stack));

        // add the created function into the functions vector of the program
        self.asm_ast_program.functions.push(asm_ast_function);
    }

    pub fn visit_tacky_store(&mut self, 
        asm_ast_function: &mut AsmAstFunction, 
        tacky_node_store: &Instruction)
    {
        // DEBUG
        println!("{:?}", tacky_node_store);

        //
        // Store - Conversion is explained on page 376 and defined again on 378
        //

/* WARUM ????????????*/
        //
        // 1. Mov = Mov(Quadword, ptr, Reg(AX))
        //

        let mut mov_1: AsmAstInstruction = AsmAstInstruction::new();
        mov_1.instruction_type = AsmAstInstructionType::Mov;
        mov_1.comment = String::from(format!("    ; TACKY Store() - 1").to_string());

        // match &tacky_node_store.src {
        //     ValueElement::Variable(var_name) => {
        //         mov_1.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
        //     }
        //     ValueElement::Constant(constant_value) => {
        //         mov_1.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
        //     }
        //     _ => {
        //         panic!("Need variable or Constant! Got {:?}", &tacky_node_store.src);
        //     }
        // }

        // move the destination pointer of the store into src of the first move
        match &tacky_node_store.dst {
            ValueElement::Variable(var_name) => {
                mov_1.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
            }
            ValueElement::Constant(constant_value) => {
                mov_1.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            _ => {
                panic!("Need variable! Got {:?}", &tacky_node_store.src);
            }
        }

        // move the pointer into AX
        mov_1.dst = AsmAstOperand { operand_type: AsmAstOperandType::Reg(AsmAstReg::AX) };

        asm_ast_function.body.push(Box::new(mov_1));


        //
        // 2. Mov = Mov(<dst_type>, Memory(AX, 0), dst)
        //

        let mut mov_2: AsmAstInstruction = AsmAstInstruction::new();
        mov_2.instruction_type = AsmAstInstructionType::Mov;
        match &tacky_node_store.src {
            ValueElement::Variable(var_name) => {
                //mov_2.src = AsmAstOperand { operand_type: AsmAstOperandType::Memory(AsmAstReg::AX, 0) };
                mov_2.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
            }
            ValueElement::Constant(constant_value) => {
                mov_2.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            _ => {
                panic!("Need variable or Constant! Got {:?}", &tacky_node_store.src);
            }
        }
        match &tacky_node_store.dst {
            ValueElement::Variable(var_name) => {
                //mov_2.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
                mov_2.dst = AsmAstOperand { operand_type: AsmAstOperandType::Memory(AsmAstReg::AX, 0) };
            }
            _ => {
                panic!("Need variable!");
            }
        }

        asm_ast_function.body.push(Box::new(mov_2));
    }

    pub fn visit_tacky_load(&mut self, 
        asm_ast_function: &mut AsmAstFunction, 
        tacky_node_load: &Instruction)
    {
        println!("{:?}", tacky_node_load);

        //
        // Load - Conversion is explained on page 376 and defined again on 378
        //

        //
        // 1. Mov = Mov(Quadword, ptr, Reg(AX))
        //

        let mut mov_1: AsmAstInstruction = AsmAstInstruction::new();
        mov_1.instruction_type = AsmAstInstructionType::Mov;
        mov_1.comment = String::from(format!("    ; TACKY Load()").to_string());

        match &tacky_node_load.src {
            ValueElement::Variable(var_name) => {
                mov_1.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
            }
            ValueElement::Constant(constant_value) => {
                mov_1.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            _ => {
                panic!("Need variable or Constant! Got {:?}", &tacky_node_load.src);
            }
        }
        match &tacky_node_load.dst {
            ValueElement::Variable(var_name) => {
                mov_1.dst = AsmAstOperand { operand_type: AsmAstOperandType::Reg(AsmAstReg::AX) };
            }
            _ => {
                panic!("Need variable! Got {:?}", &tacky_node_load.src);
            }
        }

        asm_ast_function.body.push(Box::new(mov_1));

        //
        // 2. Mov = Mov(<dst_type>, Memory(AX, 0), dst)
        //

        let mut mov_2: AsmAstInstruction = AsmAstInstruction::new();
        mov_2.instruction_type = AsmAstInstructionType::Mov;
        match &tacky_node_load.src {
            ValueElement::Variable(var_name) => {
                mov_2.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
            }
            _ => {
                panic!("Need variable!");
            }
        }
        match &tacky_node_load.dst {
            ValueElement::Variable(var_name) => {
                mov_2.src = AsmAstOperand { operand_type: AsmAstOperandType::Memory(AsmAstReg::AX, 0) };
            }
            ValueElement::Constant(constant_value) => {
                mov_2.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            _ => {
                panic!("Need variable or Constant! Got {:?}", &tacky_node_load.src);
            }
        }

        asm_ast_function.body.push(Box::new(mov_2));
    }

    pub fn visit_tacky_get_address(&mut self, 
        asm_ast_function: &mut AsmAstFunction, 
        tacky_node_get_address: &Instruction)
    {
        println!("{:?}", tacky_node_get_address);

        //
        // Lea - see page 378
        //

        let mut lea: AsmAstInstruction = AsmAstInstruction::new();
        lea.instruction_type = AsmAstInstructionType::Lea;
        lea.comment = String::from(format!("    ; lea for GetAddress()").to_string());
        match &tacky_node_get_address.src {
            ValueElement::Variable(var_name) => {
                lea.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
            }
            _ => {
                panic!("Need variable!");
            }
        }
        match &tacky_node_get_address.dst {
            ValueElement::Variable(var_name) => {
                // not allowed to lea into memory, the destination has to be a register
                //lea.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };

                lea.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
            }
            _ => {
                panic!("Need variable!");
            }
        }

        asm_ast_function.body.push(Box::new(lea));

        //
        // MOVE RBX to destination memory 
        //

        //
        // 2. Mov = Mov(<dst_type>, Memory(AX, 0), dst)
        //

        let mut mov_2: AsmAstInstruction = AsmAstInstruction::new();
        mov_2.instruction_type = AsmAstInstructionType::Mov;
        mov_2.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
        match &tacky_node_get_address.dst {
            ValueElement::Variable(var_name) => {
                mov_2.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(var_name.clone()) };
            }
            // ValueElement::Constant(constant_value) => {
            //     mov_2.dst = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            // }
            _ => {
                panic!("Need variable or Constant! Got {:?}", &tacky_node_get_address.dst);
            }
        }

        asm_ast_function.body.push(Box::new(mov_2));
    }

    // Nora Sandler, page 195
    pub fn visit_tacky_fun_call_system_v_abi(&mut self, 
        asm_ast_function: &mut AsmAstFunction, 
        tacky_node_fun_call: &Instruction) 
    {
        println!("{:?}", tacky_node_fun_call);

        //
        // allocate stack
        //

        let total_param_count:usize = tacky_node_fun_call.parameters.len();

        // in System-V abi the first 6 arguments go into registers and the rest goes onto the stack.
        // Only if there are register on the stack can the stack be misaligned.
        //
        // For some reason stack addresses can only ever by multiple of 16 bit!
        // The address needs to be aligned correctly by moving it to a address divisible by 16 bit

        // System-V
        let mut stack_padding:usize = 0usize;
        if total_param_count > 6 {
            if total_param_count % 2 != 0 {
                stack_padding = 8;
            }
        }

        // ALLOCATE_STACK
        // insert allocate stack instruction - page ???
        //
        // allocate space for parameters that need to go onto the stack according to the ABI
        let mut allocate_stack: AsmAstInstruction = AsmAstInstruction::new();
        allocate_stack.instruction_type = AsmAstInstructionType::AllocateStack;
        allocate_stack.src.operand_type = AsmAstOperandType::Imm(stack_padding as i32);
        allocate_stack.comment = String::from("\n    ; FunctionCall - Allocate space for parameters that need to go onto the stack according to the ABI - [AsmAstConversionVisitor::visit_tacky_fun_call_system_v_abi()]");

        asm_ast_function.body.push(Box::new(allocate_stack));

        //
        // Move first six (System-V ABI) or first 4 (Win64 Fastcall) parameters into registers - pass args in register - page 198
        //

        // System-V ABI
        for (index, param) in tacky_node_fun_call.parameters.iter().enumerate() {

            if index >= 6 {
                continue;
            }

            if index < 6 {
                println!("[REGISTER] ARGUMENT_{} - Value:{:?} - Register:{:?}", index, param, SYSTEM_V_ABI_REGISTER_ORDER[index]);
            }

            //
            // Mov
            //

            let mut mov: AsmAstInstruction = AsmAstInstruction::new();
            mov.instruction_type = AsmAstInstructionType::Mov;
            mov.comment = String::from(format!("    ; mov into register fun_call argument {}", index).to_string());

            match param.as_ref() {
                ValueElement::Constant(constant_value) => {
                    mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                }
                ValueElement::Variable(variable_name) => {
                    mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                }
                _ => {
                    panic!("{}", format!("Unhandled InstructionType {:?}!\n", param).as_str());
                }
            }

            mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(SYSTEM_V_ABI_REGISTER_ORDER[index].clone()) };

            asm_ast_function.body.push(Box::new(mov));
        }

        //
        // Push arguments to the stack according to the ABI (first arguments go into register )
        //
        
        // System-V ABI
        for i in (6..total_param_count).rev() {
            println!("test {}", i);
            println!("{:?}", tacky_node_fun_call.parameters[i]);

            let mut push: AsmAstInstruction = AsmAstInstruction::new();
            push.instruction_type = AsmAstInstructionType::Push;
            push.comment = String::from(format!("    ; push fun_call argument {}", i).to_string());
            match tacky_node_fun_call.parameters[i].as_ref() {
                ValueElement::Constant(constant_value) => {
                    push.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                }
                ValueElement::Variable(variable_name) => {
                    push.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                }
                _ => {
                    panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_fun_call.parameters[i]).as_str());
                }
            }

            asm_ast_function.body.push(Box::new(push));
        }
        // println!("test");

        //
        // emit 'call' instruction
        //
        // 'call' mnemonic (Places return address (address of next instruction) 
        // onto the stack and jumps to the function's label (set Instruction Pointer to address))
        //

        let mut fun_call: AsmAstInstruction = AsmAstInstruction::new();
        fun_call.instruction_type = AsmAstInstructionType::FunctionCall;
        fun_call.identifier = tacky_node_fun_call.function_name.clone();

        asm_ast_function.body.push(Box::new(fun_call));

        //
        // adjust stack pointer - needs to be adjusted if there are more than 6 parameters because they go to the stack
        //
        // deallocate stack
        //

        // System-V ABI
        if total_param_count > 6 {

            // more than 6 parameters go onto the stack and potentially cause stack_padding (when odd-numbered)
            let bytes_to_remove: usize = 8 * (total_param_count - 6) + stack_padding;
            if bytes_to_remove > 0 {

                let mut deallocate_stack: AsmAstInstruction = AsmAstInstruction::new();
                deallocate_stack.instruction_type = AsmAstInstructionType::DeallocateStack;
                deallocate_stack.src.operand_type = AsmAstOperandType::Imm(bytes_to_remove as i32);

                asm_ast_function.body.push(Box::new(deallocate_stack));
            }
        }

        //
        // TODO retrieve return value - move return value into EAX register which contains the return value in System-V ABI
        //

        // 
        // TODO: move value from EAX into the destination register as defined by TACKY
        //

        println!("tacky_node_fun_call.dst: {:?}", tacky_node_fun_call.dst);

        //
        // Mov - move value from EAX into the destination register as defined by TACKY
        //

        let mut mov: AsmAstInstruction = AsmAstInstruction::new();
        mov.instruction_type = AsmAstInstructionType::Mov;
        mov.comment = String::from(format!("    ; mov EAX into TACKY dst variable {:?}", tacky_node_fun_call.dst).to_string());
        mov.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::AX) };
        // match param.as_ref() {
        //     ValueElement::Constant(constant_value) => {
        //         mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
        //     }
        //     ValueElement::Variable(variable_name) => {
        //         mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
        //     }
        //     _ => {
        //         panic!("{}", format!("Unhandled InstructionType {:?}!\n", param).as_str());
        //     }
        // }
        // match &tacky_node_copy.dst {
        //     ValueElement::Variable(variable_name) => {
        //         mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
        //     }
        //     _ => {
        //         panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_copy.dst).as_str());
        //     }
        // }
        // mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(SYSTEM_V_ABI_REGISTER_ORDER[index].clone()) };
        // mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(tacky_node_fun_call.dst.variable_name.clone()) };
        
        match &tacky_node_fun_call.dst {

            // ValueElement::Constant(value) => {
            //     write!(f, "Constant({})", &value).expect("Write failed!");
            // }
            ValueElement::Variable(value) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(value.clone()) };
            }
            
            _ => {
                panic!("test");
            }
        }
        
        asm_ast_function.body.push(Box::new(mov));

    }

    pub fn visit_tacky_jump(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_jump: &Instruction) {
        // println!("TODO: visit_tacky_jump()");

        println!("{:?}", tacky_node_jump);

        let mut jump: AsmAstInstruction = AsmAstInstruction::new();
        jump.instruction_type = AsmAstInstructionType::Jmp;
        jump.dst = AsmAstOperand { operand_type: AsmAstOperandType::Label(tacky_node_jump.label.clone()) };

        asm_ast_function.body.push(Box::new(jump));
    }

    pub fn visit_tacky_copy(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_copy: &Instruction) {
        //println!("TODO: visit_tacky_copy()");

        // DEBUG
        println!("{:?}", tacky_node_copy);

        // sometimes copies are generated, that copy src to dst where src and dst are the same object
        // ignore those cases
        if tacky_node_copy.src == tacky_node_copy.dst {
            return;
        }

        // Instruction { 
        //      instruction_type: Copy, 
        //      src: Constant(123), 
        //      src_2: None, 
        //      dst: Variable(userdef_var.0), 
        //      unary_operator: Not, 
        //      binary_operator: Add, 
        //      label: "", 
        //      data_type: "", 
        //      function_name: "", 
        //      parameters: [], 
        //      offset: 0, 
        //      index: None, 
        //      scale: 0 
        // }

        //
        // MOV
        //
        // TACKY Unary ==> Mov + Unary
        //

        let mut mov: AsmAstInstruction = AsmAstInstruction::new();
        mov.instruction_type = AsmAstInstructionType::Mov;

        match &tacky_node_copy.src {
            ValueElement::Constant(constant_value) => {
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_copy.src).as_str());
            }
        }

        match &tacky_node_copy.dst {
            ValueElement::Variable(variable_name) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_copy.dst).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(mov));
    }

    pub fn visit_tacky_variable_declaration(&mut self, asm_ast_function: &mut AsmAstFunction) {
        println!("TODO: visit_tacky_variable_declaration()");
    }

    pub fn visit_tacky_label(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_label: &Instruction) {
        
        let mut label: AsmAstInstruction = AsmAstInstruction::new();
        label.instruction_type = AsmAstInstructionType::Label;
        label.src = AsmAstOperand { operand_type: AsmAstOperandType::Label(tacky_node_label.label.clone()) };

        asm_ast_function.body.push(Box::new(label));
    }

    // Converts or lowers a TACKY application into an ASM AST (of precursor/pseudo ASM instructions).
    //
    // Binary(LessThan, src_1:Constant(1), src_2:Constant(2), dst:Variable(tmp.0))
    // JumpIfZero(Constant(tmp.0), if_14.end_label)
    //
    // Nora Sandler, page 78 ff
    //
    // Cmp(Imm(0), condition)
    // JmpCC(E, target)
    // 
    // Nora Sandler, page 86
    //
    // JumpIfZero(val, target)
    // --->
    // Cmp(Imm(0), val)
    // JmpCC(E, target)
    pub fn visit_tacky_jump_if_zero(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_jump_if_zero: &Instruction) {
        
        println!("[AsmAstConversionVisitor::visit_tacky_jump_if_zero() {:?}]", tacky_node_jump_if_zero);

        //
        // Cmp(Imm(0), condition)
        //

        let mut cmp: AsmAstInstruction = AsmAstInstruction::new();
        cmp.instruction_type = AsmAstInstructionType::Cmp;
        cmp.dst = AsmAstOperand { 
            operand_type: AsmAstOperandType::Imm(0) 
        };

        match &tacky_node_jump_if_zero.src {

            ValueElement::Constant(constant_value) => {
                let parsed_value = i32::from_str_radix(&constant_value, 10).expect("REASON");
                cmp.src_2 = AsmAstOperand { 
                    operand_type: AsmAstOperandType::Imm(parsed_value) 
                };
            }

            ValueElement::Variable(variable_name) => {
                println!("{}", variable_name);
                cmp.src_2 = AsmAstOperand { 
                    operand_type: AsmAstOperandType::Pseudo(variable_name.clone())
                };
            }

            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_jump_if_zero.src).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(cmp));

        //
        // JmpCC(E, target)
        //

        let mut jump_cc: AsmAstInstruction = AsmAstInstruction::new();
        jump_cc.instruction_type = AsmAstInstructionType::JmpCC;
        jump_cc.src = AsmAstOperand { operand_type: AsmAstOperandType::ComparisonType(String::from("E")) }; // E as in Equal
        jump_cc.dst = AsmAstOperand { operand_type: AsmAstOperandType::Label(tacky_node_jump_if_zero.label.clone()) };

        asm_ast_function.body.push(Box::new(jump_cc));
    }

    pub fn visit_tacky_return(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_return: &Instruction) {
        println!("[AsmAstConversionVisitor::visit_tacky_return() tacky_node_return: {:?}]", tacky_node_return);
        // println!("[AsmAstConversionVisitor::visit_tacky_return() asm_ast_function: {:?}]", asm_ast_function);

        // This move will move the returned value into the ABI register EAX which is defined to contain the
        // return value. If the function has void return type, do not add this move!
        if let Some(r_type) = &asm_ast_function.return_type {

            if *r_type != DataType::DataTypeVoid {

                // mov eax, src
                let mut mov: AsmAstInstruction = AsmAstInstruction::new();
                mov.instruction_type = AsmAstInstructionType::Mov;
                mov.comment = String::from("    ; Generated by the Return keyword in asm_ast_conversion_visitor");
                match &tacky_node_return.src {
                    ValueElement::Constant(constant_value) => {
                        let parsed_value = i32::from_str_radix(&constant_value, 10).expect("REASON");
                        mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(parsed_value) };
                    }
                    ValueElement::Variable(variable_name) => {
                        mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                    }
                    ValueElement::None => {
                        // do nothing
                    }
                    // _ => {
                    //     panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_return.src).as_str());
                    // }
                }
                mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::AX) };
                asm_ast_function.body.push(Box::new(mov));

            }
        }

        // // deallocate stack
        // let mut deallocate_stack: AsmAstInstruction = AsmAstInstruction::new();
        // deallocate_stack.instruction_type = AsmAstInstructionType::DeallocateStack;
        // deallocate_stack.src.operand_type = AsmAstOperandType::Imm(120 as i32);
        // asm_ast_function.body.push(Box::new(deallocate_stack));

        // ret
        let mut ret: AsmAstInstruction = AsmAstInstruction::new();
        ret.instruction_type = AsmAstInstructionType::Ret;
        asm_ast_function.body.push(Box::new(ret));
    }

    // Nora Sandler, page 41
    //
    // Unary is implemented in TACKY as a UNARY node with a 
    // - src which is the variable or constant to increment
    // - dst which is the place to put the result into
    // - unary_operator which is the unary operation to apply (inc, dec, not, neg, complement, ...)
    //
    // This will be translated into a Mov from src to dest followed by a unary oparation using dst.
    pub fn visit_tacky_unary(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_unary: &Instruction) {
        println!("[AsmAstConversionVisitor::visit_tacky_unary()]");

        // The 'Dereference' Unary operator is resolved into it's own set of Intermediate Assembly

        match &tacky_node_unary.unary_operator {

            UnaryOperator::AddrOf => {
                todo!();
            }
            UnaryOperator::Dereference => {

                // todo!();

                println!("tacky_node_unary: {:?}", tacky_node_unary);

                let mut mov: AsmAstInstruction = AsmAstInstruction::new();
                mov.instruction_type = AsmAstInstructionType::Mov;
                match &tacky_node_unary.src {
                    ValueElement::Constant(constant_value) => {
                        mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                    }
                    ValueElement::Variable(variable_name) => {
                        mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                    }
                    _ => {
                        panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.src).as_str());
                    }
                }
                match &tacky_node_unary.dst {
                    ValueElement::Variable(variable_name) => {
                        mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                    }
                    _ => {
                        panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.dst).as_str());
                    }
                }
                asm_ast_function.body.push(Box::new(mov));

            }
            _ => {

                //
                // MOV
                //
                // TACKY Unary ==> Mov + Unary
                //

                let mut mov: AsmAstInstruction = AsmAstInstruction::new();
                mov.instruction_type = AsmAstInstructionType::Mov;
                match &tacky_node_unary.src {
                    ValueElement::Constant(constant_value) => {
                        mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                    }
                    ValueElement::Variable(variable_name) => {
                        mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                    }
                    _ => {
                        panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.src).as_str());
                    }
                }
                match &tacky_node_unary.dst {
                    ValueElement::Variable(variable_name) => {
                        mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                    }
                    _ => {
                        panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.dst).as_str());
                    }
                }
                asm_ast_function.body.push(Box::new(mov));

                //
                // UNARY
                //
                // TACKY Unary ==> Mov + Unary
                //
                
                let mut unary: AsmAstInstruction = AsmAstInstruction::new();
                unary.instruction_type = AsmAstInstructionType::Unary;
                match &tacky_node_unary.unary_operator {
                    UnaryOperator::Not | UnaryOperator::Complement => {
                        unary.unary_operator = AsmAstUnaryOperator::Not;
                    }
                    UnaryOperator::Negate => {
                        unary.unary_operator = AsmAstUnaryOperator::Neg;
                    }
                    UnaryOperator::Increment => {
                        unary.unary_operator = AsmAstUnaryOperator::Increment;
                    }
                    UnaryOperator::Dereference => {
                        // unary.unary_operator = AsmAstUnaryOperator::Dereference;

                        // Nora Sandler, page 376
                        //
                        // Mov(Quadword, ptr, Reg(AX))
                        // Mov(<dst type>, Memory(AX, 0), dst)

                        todo!();
                    }
                    UnaryOperator::AddrOf => {
                        todo!();
                    }
                    // _ => {
                    //     panic!("{}", format!("Unhandled unary_operator '{:?}'!\n", tacky_node_unary.unary_operator).as_str());
                    // }
                }
                match &tacky_node_unary.dst {
                    ValueElement::Variable(variable_name) => {
                        unary.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                    }
                    _ => {
                        panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.dst).as_str());
                    }
                }

                asm_ast_function.body.push(Box::new(unary));
            }
        }


        
    }

    // Nora Sandler, page 63
    pub fn visit_tacky_binary(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_instruction: &Instruction) {
        println!("[AsmAstConversionVisitor::visit_tacky_binary()]");

        match &tacky_instruction.binary_operator {

            BinaryOperator::Division => {
                self.visit_tacky_binary_division(asm_ast_function, tacky_instruction, &AsmAstInstructionType::Idiv);
            }
            BinaryOperator::Remainder => {
                self.visit_tacky_binary_division(asm_ast_function, tacky_instruction, &AsmAstInstructionType::Mod);
            }
            BinaryOperator::Multiply => {
                self.visit_tacky_binary_multiplication(asm_ast_function, tacky_instruction);
            }
            BinaryOperator::Equal => {
                self.visit_tacky_binary_relational(asm_ast_function, tacky_instruction, &AstNodeOperatorType::Equal);
            }
            BinaryOperator::NotEqual => {
                self.visit_tacky_binary_relational(asm_ast_function, tacky_instruction, &AstNodeOperatorType::NotEqual);
            }
            BinaryOperator::LessThan => {
                self.visit_tacky_binary_relational(asm_ast_function, tacky_instruction, &AstNodeOperatorType::LessThan);
            }
            BinaryOperator::LessThanOrEqual => {
                self.visit_tacky_binary_relational(asm_ast_function, tacky_instruction, &AstNodeOperatorType::LessThanOrEqual);
            }
            BinaryOperator::GreaterThan => {
                self.visit_tacky_binary_relational(asm_ast_function, tacky_instruction, &AstNodeOperatorType::GreaterThan);
            }
            BinaryOperator::GreaterThanOrEqual => {
                self.visit_tacky_binary_relational(asm_ast_function, tacky_instruction, &AstNodeOperatorType::GreaterThanOrEqual);
            }

            _ => {
                self.visit_tacky_binary_standard(asm_ast_function, tacky_instruction);
            }
        }
    }

    pub fn visit_tacky_binary_relational(&mut self, asm_ast_function: &mut AsmAstFunction, 
        tacky_node_binary: &Instruction, operator_type_param: &AstNodeOperatorType) {

        println!("[AsmAstConversionVisitor::visit_tacky_binary_relational()] {:?}", tacky_node_binary);

        // nora sandler, page 87
        //
        // Cmp(src2, src1) <----------- Cannot compare two immedites, needs at least one memory address or temp register. 
        //                 <----------- See visit_tacky_binary_division() or visit_tacky_binary_multiplication()
        // Mov(Imm(0), dst)
        // SetCC(relational_operator, dst)

        //
        // Cmp(src2, src1)
        //

        let mut cmp: AsmAstInstruction = AsmAstInstruction::new();
        cmp.instruction_type = AsmAstInstructionType::Cmp;

        match &tacky_node_binary.src {
            ValueElement::Constant(constant_value) => {

                // mul needs a register or memory operand to function. It cannot work with immediate values
                let mut mov: AsmAstInstruction = AsmAstInstruction::new();
                mov.instruction_type = AsmAstInstructionType::Mov;
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
                asm_ast_function.body.push(Box::new(mov));

                cmp.src_2 = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
            }
            ValueElement::Variable(variable_name) => {
                cmp.src_2 = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.src).as_str());
            }
        }

        match &tacky_node_binary.src_2 {
            ValueElement::Constant(constant_value) => {
                cmp.dst = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                cmp.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.src_2).as_str());
            }
        }

        println!("{}", cmp);

        asm_ast_function.body.push(Box::new(cmp));

        //
        // MOV, Nora Sandler, page 63
        //
        // TACKY Binary ==> Mov(src1, dst) + Binary(binary_operator, src2, dst)
        //

        let mut mov: AsmAstInstruction = AsmAstInstruction::new();
        mov.instruction_type = AsmAstInstructionType::Mov;
        mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(0) };

        match &tacky_node_binary.dst {
            ValueElement::Constant(constant_value) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.dst).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(mov));

        //
        // SetCC(relational_operator, dst)
        //

        let mut set_cc: AsmAstInstruction = AsmAstInstruction::new();
        set_cc.instruction_type = AsmAstInstructionType::SetCC;
        // set_cc.src = AsmAstOperand { operand_type: AsmAstOperandType::ComparisonType(String::from("L")) }; // L as in (L)essThan
        set_cc.src = AsmAstOperand { operand_type: AsmAstOperandType::ComparisonType(operator_type_param.to_string()) };

        match &tacky_node_binary.dst {
            ValueElement::Constant(constant_value) => {
                set_cc.dst = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                set_cc.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.dst).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(set_cc));

    }

    pub fn visit_tacky_binary_division(&mut self, asm_ast_function: &mut AsmAstFunction, 
        tacky_node_binary: &Instruction, instruction_type_param: &AsmAstInstructionType) {

        println!("[AsmAstConversionVisitor::visit_tacky_binary_division()]");

        //
        // MOV, Nora Sandler, page 63
        //
        // TACKY Binary ==> Mov(src1, dst) + Binary(binary_operator, src2, dst)
        //

        asm_ast_function.body.push(Box::new(self.move_src_to_ax(tacky_node_binary)));

        //
        // Cdq, page 63
        //

        let mut cdq: AsmAstInstruction = AsmAstInstruction::new();
        cdq.instruction_type = AsmAstInstructionType::Cdq;

        asm_ast_function.body.push(Box::new(cdq));

        //
        // Idiv, page 63
        //

        let mut idiv: AsmAstInstruction = AsmAstInstruction::new();
        idiv.instruction_type = instruction_type_param.clone();

        match &tacky_node_binary.src_2 {

            ValueElement::Constant(constant_value) => {

                // idiv needs a register or memory operand to function. It cannot work with immediate values
                let mut mov: AsmAstInstruction = AsmAstInstruction::new();
                mov.instruction_type = AsmAstInstructionType::Mov;
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
                asm_ast_function.body.push(Box::new(mov));

                idiv.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
            }
            ValueElement::Variable(variable_name) => {
                idiv.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.dst).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(idiv));

        //
        // MOV, Nora Sandler, page 63
        //
        // TACKY Binary ==> Mov(src1, dst) + Binary(binary_operator, src2, dst)
        //

        let mut mov: AsmAstInstruction = AsmAstInstruction::new();
        mov.instruction_type = AsmAstInstructionType::Mov;

        // idiv puts the division result into eax
        // idiv puts the remainder result into edx

        match instruction_type_param {
            AsmAstInstructionType::Idiv => {
                mov.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::AX) };
            }
            AsmAstInstructionType::Mod => {
                mov.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::DX) };
            }
            _ => {
                todo!();
            }
        }

        match &tacky_node_binary.dst {
            ValueElement::Constant(constant_value) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.dst).as_str());
            }
        }

        // println!("{}", mov);

        asm_ast_function.body.push(Box::new(mov));
    }

    pub fn visit_tacky_binary_remainder(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_binary: &Instruction) {
        println!("[AsmAstConversionVisitor::visit_tacky_binary_remainder()]");

        todo!();
    }

    pub fn visit_tacky_binary_multiplication(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_instruction: &Instruction) {

        // https://www.felixcloutier.com/x86/mul
        //
        // The destination operand is an implied operand located in register AL, AX or EAX (depending on the size of the operand); 
        // the source operand is located in a general-purpose register or a memory location.

        // Move first operand into EAX (which also contains the result afterwards)
        asm_ast_function.body.push(Box::new(self.move_src_to_ax(tacky_instruction)));

        // emit a mul pseudo mnemonic

        let mut mul: AsmAstInstruction = AsmAstInstruction::new();
        mul.instruction_type = AsmAstInstructionType::Mul;

        match &tacky_instruction.src_2 {

            ValueElement::Constant(constant_value) => {

                // mul needs a register or memory operand to function. It cannot work with immediate values
                let mut mov: AsmAstInstruction = AsmAstInstruction::new();
                mov.instruction_type = AsmAstInstructionType::Mov;
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
                asm_ast_function.body.push(Box::new(mov));

                mul.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };
            }

            ValueElement::Variable(variable_name) => {
                mul.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }

            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_instruction.src).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(mul));

        // move result available in EAX into the temp variable on the stack so that the final result
        // can retrieve it from the temporary variable on the stack

        //
        // MOV, Nora Sandler, page 63
        //
        // TACKY Binary ==> Mov(src1, dst) + Binary(binary_operator, src2, dst)
        //

        let mut mov: AsmAstInstruction = AsmAstInstruction::new();
        mov.instruction_type = AsmAstInstructionType::Mov;

        // idiv puts the result into eax
        mov.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::AX) };

        match &tacky_instruction.dst {
            ValueElement::Constant(constant_value) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_instruction.src).as_str());
            }
        }

        println!("{}", mov);

        asm_ast_function.body.push(Box::new(mov));
    }

    pub fn visit_tacky_binary_standard(&mut self, asm_ast_function: &mut AsmAstFunction, tacky_node_binary: &Instruction) {
        println!("[AsmAstConversionVisitor::visit_tacky_binary_standard()]");

        //
        // MOV, Nora Sandler, page 63
        //
        // TACKY Binary ==> Mov(src1, dst) + Binary(binary_operator, src2, dst)
        //

        let mut mov: AsmAstInstruction = AsmAstInstruction::new();
        mov.instruction_type = AsmAstInstructionType::Mov;

        match &tacky_node_binary.src {
            ValueElement::Constant(constant_value) => {
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.src).as_str());
            }
        }

        match &tacky_node_binary.dst {
            ValueElement::Variable(variable_name) => {
                mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.dst).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(mov));

        //
        // BINARY, Nora Sandler, page 63
        //
        // TACKY Binary ==> Mov(src1, dst) + Binary(binary_operator, src2, dst)
        //

        let mut binary: AsmAstInstruction = AsmAstInstruction::new();
        binary.instruction_type = AsmAstInstructionType::Binary;
        match &tacky_node_binary.binary_operator {

            BinaryOperator::Add => {
                binary.binary_operator = AsmAstBinaryOperator::Add;
            }

            BinaryOperator::Subtract => {
                binary.binary_operator = AsmAstBinaryOperator::Subtract;
            }

            BinaryOperator::Multiply => {
                binary.binary_operator = AsmAstBinaryOperator::Multiply;
            }

            BinaryOperator::Equal => {
                binary.binary_operator = AsmAstBinaryOperator::Equal;
            }

            BinaryOperator::NotEqual => {
                binary.binary_operator = AsmAstBinaryOperator::NotEqual;
            }

            BinaryOperator::LessThan => {
                binary.binary_operator = AsmAstBinaryOperator::LessThan;
            }

            BinaryOperator::LessThanOrEqual => {
                binary.binary_operator = AsmAstBinaryOperator::LessThanOrEqual;
            }

            BinaryOperator::GreaterThan => {
                binary.binary_operator = AsmAstBinaryOperator::GreaterThan;
            }

            BinaryOperator::GreaterThanOrEqual => {
                binary.binary_operator = AsmAstBinaryOperator::GreaterThanOrEqual;
            }

            _ => {
                panic!("{}", format!("Unhandled BinaryOperator {:?}!\n", tacky_node_binary.binary_operator).as_str());
            }
        }

        match &tacky_node_binary.src_2 {
            ValueElement::Constant(constant_value) => {
                println!("{}", constant_value);
                binary.src_2 = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
            }
            ValueElement::Variable(variable_name) => {
                binary.src_2 = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.src_2).as_str());
            }
        }

        match &tacky_node_binary.dst {
            ValueElement::Variable(variable_name) => {
                binary.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            }
            _ => {
                panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_binary.dst).as_str());
            }
        }

        asm_ast_function.body.push(Box::new(binary));
    }
}

// // unary.src = tacky_node_unary.src.clone();
// match &tacky_node_unary.src {
//     ValueElement::Constant(constant_value) => {
//         unary.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
//     }
//     ValueElement::Variable(variable_name) => {
//         unary.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
//     }
//     _ => {
//         panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.src).as_str());
//     }
// }

// match &tacky_node_unary.src {
//     ValueElement::Variable(variable_name) => {
//         unary.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
//     }
//     _ => {
//         panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.src).as_str());
//     }
// }

// match &tacky_node_unary.src {
//     ValueElement::Variable(variable_name) => {
//         unary.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
//     }
//     _ => {
//         panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_unary.src).as_str());
//     }
// }

// mov.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };

// mov.src = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(AsmAstReg::BX) };



/*
            //
            // Mov - page 198 - move arguments to the stack
            //

            let mut mov: AsmAstInstruction = AsmAstInstruction::new();
            mov.instruction_type = AsmAstInstructionType::Mov;

            match param.as_ref() {
                ValueElement::Constant(constant_value) => {
                    mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                }
                ValueElement::Variable(variable_name) => {
                    mov.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                }
                _ => {
                    panic!("{}", format!("Unhandled InstructionType {:?}!\n", param).as_str());
                }
            }

            // match &tacky_node_copy.dst {
            //     ValueElement::Variable(variable_name) => {
            //         mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            //     }
            //     _ => {
            //         panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_copy.dst).as_str());
            //     }
            // }

            //mov.dst = AsmAstOperand{ operand_type: AsmAstOperandType::Reg(system_V_ABI_Register_order[index].clone()) };

            // AsmAstOperand{ operand_type: AsmAstOperandType::Stack(i32),
            mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Stack(stack_offset_value) };

            asm_ast_function.body.push(Box::new(mov));
*/

/*
        for (index, param) in tacky_node_fun_call.parameters.iter().enumerate() {

            if index < 6 {
                continue;
            }

            if index >= 6 {
                println!("[STACK] ARGUMENT_{}: {:?}", index, param);
            }

            let mut push: AsmAstInstruction = AsmAstInstruction::new();
            push.instruction_type = AsmAstInstructionType::Push;

            match param.as_ref() {
                ValueElement::Constant(constant_value) => {
                    push.src = AsmAstOperand { operand_type: AsmAstOperandType::Imm(i32::from_str_radix(&constant_value, 10).expect("REASON")) };
                }
                ValueElement::Variable(variable_name) => {
                    push.src = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
                }
                _ => {
                    panic!("{}", format!("Unhandled InstructionType {:?}!\n", param).as_str());
                }
            }

            asm_ast_function.body.push(Box::new(push));
        }
*/



            // match &tacky_node_copy.dst {
            //     ValueElement::Variable(variable_name) => {
            //         mov.dst = AsmAstOperand { operand_type: AsmAstOperandType::Pseudo(variable_name.clone()) };
            //     }
            //     _ => {
            //         panic!("{}", format!("Unhandled InstructionType {:?}!\n", tacky_node_copy.dst).as_str());
            //     }
            // }